---
permalink: administration/reference_snap_creator_terminology.html 
sidebar: sidebar 
keywords: snap, creator, terminology,action, backup, lun, clone, volume, agent, monitor, archive, log, configuration, discover, global, job, mount, ossv, profile, policy, quiesce, restore, scdump, schedule, umount, unquiesce, watchdog 
summary: SnapCreator由幾個不同的架構所組成、因此務必瞭解其語言和概念。 
---
= SnapCreator術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCreator由幾個不同的架構所組成、因此務必瞭解其語言和概念。

* *行動*
+
SnapCreator可在組態檔案上執行各種動作。這通常是一個定義好的工作流程、可達成所需的結果。若要執行某項動作、請從GUI選取組態檔、按一下「*動作*」、然後從下拉式清單中選取下列其中一個動作：

+
** *備份*
+
備份組態檔中指定的環境。備份工作流程是一項多步驟動作、會根據所選組態檔的設定而變更。設定外掛程式的備份動作範例包括：靜止應用程式或資料庫、取得所有已定義磁碟區的Snapshot複本、取消靜止所選應用程式或資料庫、執行SnapVault 更新或SnapMirror或SnapMirror、執行任何保留原則、或是執行任何歸檔記錄設定。

** * LUN複製*
+
建立LUN的新Snapshot複本、並複製新的Snapshot複本。

** * Volume Clone *
+
建立磁碟區的新Snapshot複本、並複製新的Snapshot複本。



* *代理監控*
+
代理程式監視器會查詢Snap Creator伺服器、以取得組態檔中定義的所有代理程式、並查詢代理程式以檢查其狀態。代理程式監控會報告代理程式是否在執行、代理程式正在偵聽的連接埠、以及代理程式的版本是否在使用中。

* *歸檔日誌*
+
歸檔記錄動作會對組態檔的歸檔記錄管理設定中的任何設定執行。此動作通常會清除Snap Creator不再需要的記錄。

* *組態檔*
+
組態檔是Snap Creator的核心。它會設定Snap Creator、讓應用程式外掛程式能夠執行、設定必要的變數、並定義Snapshot複本中擷取的磁碟區。組態檔由不同的參數組成、這些參數可設定為影響Snap Creator的行為。組態檔通常會縮短為組態或組態。

* *探索*
+
「探索」動作會在組態檔中詳述的環境中執行儲存層級探索。並非所有外掛程式都支援探索。

* *全域組態檔*
+
可在超級全域層級（參數會影響整個Snap Creator Server環境中的所有組態檔）或設定檔層級（參數會影響指定設定檔中的所有組態檔）運作的組態檔。超全域參數將會被設定檔層級全域中指定的任何參數覆寫。同樣地、組態檔中指定的參數也會覆寫超級或設定檔層級通用組態檔中的任何參數。通用組態檔通常會縮短為全域組態。

* *工作*
+
所有由Snap Creator執行的作業均視為工作。部分動作可能包含多個工作。所有由Snap Creator執行的工作都會列在「工作監控」中。

* *工作監控*
+
工作監控器是易於使用的儀表板介面、可讓您輕鬆查看正在執行或先前已執行之Snap Creator工作的狀態。設定時會啟用「工作監控」、可儲存1至1、000個工作。

* *掛載*
+
掛載動作可讓您指定要複製及掛載的現有Snapshot複本。

* * OSSV*
+
OSSV（開放式系統SnapVault ）動作執行OSSV作業。

* *設定檔*
+
設定檔基本上是用來組織組態檔的資料夾。設定檔也可做為角色型存取控制（RBAC）的物件、這表示您只能存取其中包含的特定設定檔和組態檔。

* *政策*
+
保留政策不適用。原則通常會定義Snapshot保留原則（要保留多少Snapshot複本）和期限（Snapshot複本刪除之前的期限）。例如、每日原則可能會保留至少30天的Snapshot複本價值。（保留期限設定可防止同一天拍攝的多個Snapshot複本繞過SLA、因為SLA可能會指出Snapshot複本需要30天。） 如果使用了此功能、則原則也會定義任何有關該版本的保留設定。SnapVault SnapVault目前的原則可以直接儲存在組態檔中、也可以儲存為原則物件的一部分。如果原則是組態檔的一部分、則可能稱為本機保留原則。

* *原則物件*
+
原則物件是可在設定檔層級套用的保留原則。如同原則、原則物件會定義保留原則、但也可以定義排程和標籤。以下是原則物件的元件：

+
** *備份類型*
+
備份類型是原則物件可以設定的標籤。

** *原則指派*
+
原則指派會將原則（在原則管理中建立）指派給設定檔的特定設定檔。

** *政策管理*
+
原則管理會在原則物件內建立原則。這可定義Snapshot複本的保留計數和保留時間。如果使用了此功能、也可以設定相關的保留計數和保留期限。SnapVault原則管理也允許選擇性地選取原則排程和備份類型。

** *政策時間表*
+
原則排程會定義要在指定排程上採取的動作。



* *靜止*
+
「靜止」動作會執行必要的動作、將應用程式或資料庫置於一致的狀態。雖然動作名稱為quiesce、但視外掛程式或組態檔設定而定、這可能不是真正的靜止作業。例如、Domino外掛程式會執行Domino API呼叫、將Domino資料庫置於備份開始狀態、而DB2外掛程式則會執行DB2寫入暫停命令。

* *還原*
+
還原動作會在組態檔中指定的一或多個磁碟區上執行磁碟區或單一檔案還原作業。視組態檔中使用的外掛程式而定、可能會有其他的還原作業可用。

* * scdump *
+
scdump是一項疑難排解作業、可在設定檔層級收集所有組態檔案和記錄檔、並收集一些標準的Snap Creator Server記錄檔和環境資訊。所有這些收集到的檔案都會壓縮成一個壓縮檔、系統會提示您下載。然後、scdump Zip檔案可以透過電子郵件傳送或上傳至Support進行分析。

* *排程*
+
Snap Creator伺服器包含集中式排程器。這可讓您透過原則排程（原則物件的一部分）或透過排程器直接建立SnapCreator工作。排程器可同時執行多達10個工作、並在執行中的工作完成之前佇列其他工作。

* * SnapCreator代理程式*
+
SnapCreator Agent通常安裝在安裝應用程式或資料庫的同一主機上。代理程式是外掛程式所在的位置。有時、在Snap Creator中、代理程式會縮短為scAgent。

* * SnapCreator Framework*
+
SnapCreator是一個架構、完整產品名稱為NetApp Snap Creator Framework。

* * Snap Creator外掛程式*
+
外掛程式用於將應用程式或資料庫置於一致的狀態。SnapCreator包含數個外掛程式、這些外掛程式已經是二進位檔案的一部分、不需要任何額外安裝。

* * Snap Creator Server*
+
SnapCreator Server通常安裝在實體或虛擬主機上。伺服器裝載SnapCreator GUI和必要的資料庫、以儲存有關工作、排程、使用者、角色、設定檔、 組態檔、以及外掛程式的中繼資料。伺服器有時會縮短為Snap Creator中的scServer。

* * umount*
+
umount動作可讓您指定要卸載的現有掛載點。

* *取消靜止*
+
取消靜止動作會執行必要的動作、將應用程式或資料庫恢復為正常作業模式。雖然動作命名為unquiesce、但視外掛程式或組態檔設定而定、這可能不是真正的靜止作業。例如、Domino外掛程式會執行Domino API呼叫、將Domino資料庫置於備份停止狀態、而DB2外掛程式則會執行WRITE RESUME命令。

* * Watchdch*
+
監視程式是Snap Creator Agent的一部分、可監控代理程式正在執行的工作狀態。如果代理程式未在指定時間內回應、則監視程式可以重新啟動代理程式或結束特定動作。例如、如果靜止作業超過逾時值、則監視程式可以停止靜止動作並啟動靜止、使資料庫恢復正常作業模式。


