---
permalink: administration/reference_snap_creator_cli_commands_for_workflow_actions.html 
sidebar: sidebar 
keywords: command-line, interface, cli, snap, creator, workflow, command, backup, copy 
summary: 您可以使用命令列介面（CLI）命令、執行各種以圖形使用者介面（GUI）為基礎的Snap Creator工作流程動作。 
---
= SnapCreator CLI命令、以執行工作流程動作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用命令列介面（CLI）命令、執行各種以圖形使用者介面（GUI）為基礎的Snap Creator工作流程動作。

下表提供用於執行Snap Creator GUI型工作流程動作的CLI命令：

|===
| 工作流程區域 | 行動/說明 | 命令及相關參數 


 a| 
備份
 a| 
建立備份複本。根據與設定檔相關的組態檔執行備份作業。
 a| 
[listing]
----

                  snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action backup
--policy Policy
--verbose
----


 a| 
建立開放式系統SnapVault 的支援區。使用開放式系統SnapVault 功能區執行備份作業。這需要Snap Creator代理程式。SnapCreator Server會與Snap Creator Agent通訊、並執行SnapVault 更新。不製作主要備份複本。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action ossv
--policy Policy
--verbose
---- a| 
備份（續...）



 a| 
刪除備份複本（手動）。手動刪除現有的備份。此作業是功能表驅動的。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action backupDel
--policy Policy
--verbose
---- a| 
刪除備份複本（自動）。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action backupDel
--policy Policy
--verbose
--nonInteractive
--cntName controller
--volName volume
--backupName name
---- a| 
列出備份複本。列出主要和次要儲存系統上的Snap Creator備份複本。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action backupList
--policy Policy
--verbose
----


 a| 
掛載備份複本。在現有備份上執行掛載作業。根據備份建立Volume Clone、並使用mount_CMD命令透過Snap Creator Agent來掛載Clone。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action mount
--backupName name
--verbose
---- a| 
備份（續...）



 a| 
卸載備份複本。在現有備份上執行卸載作業。根據備份刪除Volume Clone、並使用umount_cmds命令、透過Snap Creator Agent卸載實體複本。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action umount
--backupName name
--verbose
---- a| 
備份類型



 a| 
建立新的備份類型。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action backupTypeAdd
--backupTypeName name
--verbose
---- a| 
更新現有的備份類型。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action backupTypeUpdate
--backupTypeId 1
--backupTypeName name
--verbose
---- a| 
刪除現有的備份類型。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action backupTypeDelete
--backupTypeId 1

--verbose
----


 a| 
列出備份類型。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action backupTypeList
--verbose
---- a| 
複製



 a| 
複製LUN.備份主要儲存系統、然後使用LUN複製來複製備份。也會處理igroup的Volume對應。這需要SAN或Isan環境。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action cloneLun
--policy Policy
--verbose
---- a| 
複製Volume。備份主要儲存系統、然後使用Volume Clone複製備份。也會處理igroup、NFS或CIFS的Volume對應。這需要SAN、Isan或NAS環境。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action cloneVol
--policy Policy
--verbose
---- a| 
刪除複本。根據指定的保留原則執行複本刪除作業。只保留一個LUN複本。Volume複製具有與原則相關的使用量。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action cloneDel
--policy Policy
--verbose
----


 a| 
列出Snap Creator複製。列出指定組態的Snap Creator Volume複製。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action cloneList
--verbose
---- a| 
列出Snap Creator磁碟區。列出主儲存系統上指定組態的Snap Creator磁碟區。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action volumeList
--verbose
---- a| 
組態檔
 a| 
匯入組態。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action configImport
--importFile file_path
--verbose
---- a| 
匯出組態。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action configExport
--exportFile file_path
--verbose
----


 a| 
匯入全域組態檔。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action globalImport
--importFile file_path
--verbose
---- a| 
匯出全域組態檔。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action globalExport
--ExportFile file_path
--verbose
---- a| 
從儲存庫刪除全域組態檔。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action globalDelete
--verbose
----


 a| 
組態檔（續...）
 a| 
將特定設定檔的全域組態檔匯入儲存庫。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileglobalImport
--importFile file_path
--verbose
----


 a| 
從儲存庫匯出特定設定檔的全域組態檔。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileglobalExport
--exportFile file_path
--verbose
---- a| 
從儲存庫中刪除特定設定檔的全域組態。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileglobalDelete
--verbose
---- a| 
升級設定檔中的舊組態檔。新增參數至較舊的組態檔。在執行此命令之前、所有舊的組態檔都必須連同設定檔資料夾一起複製到scServer/enger/configs資料夾。
 a| 
[listing]
----
snapcreator
--server IP
--port port
--user userid
--passwd password
--upgradeConfigs
--profile profile_name
--verbose
----


 a| 
工作
 a| 
列出所有工作及其狀態。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action jobStatus
--verbose
----


 a| 
原則
 a| 
新增本機原則。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyAdd
--schedId 1
--backupTypeId 1
--policyType local
--policyName testPolicy
--primaryCount 7
--primaryAge 0
--verbose
----


 a| 
原則（續...）
 a| 
新增SnapMirror原則。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyAdd
--schedId 1
--backupTypeId 1
--policyType snapmirror
--policyName testPolicy
--primaryCount 7
--primaryAge 0
--verbose
----


 a| 
新增SnapVault 功能更新原則。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyAdd
--schedId 1
--backupTypeId 1
--policyType snapvault
--policyName testPolicy
--primaryCount 7
--primaryAge 0
--secondaryCount 30
--secondaryAge 0
--verbose
---- a| 
更新SnapMirror原則。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyUpdate
--policyId 1
--schedId 1
--backupTypeId 1
--policyType snapmirror
--policyName testPolicy
--primaryCount 7
--primaryAge 0
--verbose
---- a| 
原則（續...）
 a| 
更新SnapVault 一套更新的功能。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyUpdate
--policyId 1
--schedId 1
--backupTypeId 1
--policyType snapvault
--policyName testPolicy
--primaryCount 7
--primaryAge 0
--secondaryCount 30
--secondaryAge 0
--verbose
---- a| 
刪除原則。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyDelete
--policyId 1
--verbose
----


 a| 
列出所有原則。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyList
--verbose
---- a| 
顯示特定原則的其他詳細資料。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyDetails
--policyId 1
--verbose
---- a| 
將原則指派給設定檔。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action policyAssignToProfile
--policies testPolicy
--verbose
----


 a| 
原則（續...）
 a| 
復原設定檔的原則指派。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action policyUnassignFromProfile
--verbose
----


 a| 
列出指派給設定檔的所有原則。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action policyListForProfile
--verbose
---- a| 
原則排程



 a| 
建立每小時原則排程。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedAdd
--schedName HourlyBackup
--schedFreqId 2
--schedActionId 1
--schedMin minute
--schedActive true
--verbose
---- a| 
建立每日原則排程。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedAdd
--schedName DailyBackup
--schedFreqId 3
--schedActionId 1
--schedHour hour
--schedMin minute
--schedActive true
--verbose
---- a| 
原則排程（續...）
 a| 
建立每週原則排程。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedAdd
--schedName WeeklyBackup
--schedFreqId 4
--schedActionId 1
--schedDayOfWeek day_of_week
--schedHour hour
--schedMin minute
--schedActive true
--verbose
---- a| 
建立cron原則排程。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedAdd
--schedName CronBackup
--schedFreqId 5
--schedActionId 1
--schedCron '0 0/5 14,18 * * ?'
--schedActive true
--verbose
----


 a| 
更新每小時的原則排程。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedUpdate
--schedId 1
--schedName HourlyBackup
--schedFreqId 2
--schedActionId 1
--schedMin minute
--schedActive true
--verbose
---- a| 
原則排程（續...）



 a| 
更新每日原則排程。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedUpdate
--schedId 1
--schedName DailyBackup
--schedFreqId 3
--schedActionId 1
--schedHour hour
--schedMin minute
--schedActive true
--verbose
---- a| 
更新每週原則排程。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedUpdate
--schedId 1
--schedName WeeklyBackup
--schedFreqId 4
--schedActionId 1
--schedDayOfWeek day_of_week
--schedHour hour
--schedMin minute
--schedActive true
--verbose
---- a| 
更新cron原則排程。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedUpdate
--schedId 1
--schedName CronBackup
--schedFreqId 5
--schedActionId 1
--schedCron '0 0/5 14,18 * * ?'
--schedActive true
--verbose
----


 a| 
原則排程（續...）
 a| 
刪除原則排程。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedDelete
--schedId 1
--verbose
----


 a| 
列出原則排程。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedList
--verbose
---- a| 
顯示原則排程的其他資訊。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedDetails
--schedId 1
--verbose
---- a| 
設定檔
 a| 
建立新的設定檔。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileCreate
--verbose
---- a| 
刪除設定檔。*注意：*設定檔中的組態檔也會被刪除。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileDelete
--verbose
----


 a| 
還原
 a| 
執行互動式還原。針對特定原則執行互動式檔案還原作業或互動式磁碟區還原作業。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action restore
--policy Policy
--verbose
----


 a| 
執行非互動式Volume還原。執行非互動式Volume還原。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action restore
--policy Policy
--verbose
--nonInteractive
--cntName controller
--volName volume
--backupName name
---- a| 
執行非互動式檔案還原。執行非互動式檔案還原。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action restore
--policy Policy
--verbose
--nonInteractive
--cntName controller
--volName volume
--backupName name
--files file_path1,file_path2,etc.
---- a| 
排程
 a| 
建立新的每小時排程。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedCreate
--policy Policy
--schedName HourlyBackup
--schedFreqId 2
--schedActionId 1
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
---- a| 
建立新的每日排程。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedCreate
--policy Policy
--schedName DailyBackup
--schedFreqId 3
--schedActionId 1
--schedHour hour
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
----


 a| 
建立新的每週排程。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedCreate
--policy Policy
--schedName WeeklyBackup
--schedFreqId 4
--schedActionId 1
--schedDayOfWeek day_of_week
--schedHour hour
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
---- a| 
排程（續...）



 a| 
建立新的cron排程。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedCreate
--policy Policy
--schedName CronBackup
--schedFreqId 5
--schedActionId 1
--schedCron "0 0/5 14,18 * * ?"
--schedActive true
--schedStartDate date
--verbose
---- a| 
執行排程。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedRun
--schedId 1
--verbose
---- a| 
刪除排程。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedDelete
--schedId 10
--verbose
----


 a| 
更新每小時排程。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedUpdate
--policy Policy
--schedName HourlyBackup
--schedFreqId 2
--schedId 1
--schedActionId 1
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
---- a| 
排程（續...）



 a| 
更新每日排程。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedUpdate
--policy Policy
--schedName DailyBackup
--schedFreqId 3
--schedId 1
--schedActionId 1
--schedHour hour
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
---- a| 
更新每週排程。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedUpdate
--policy Policy
--schedName WeeklyBackup
--schedFreqId 4
--schedId 1
--schedActionId 1
--schedDayOfWeek day_of_week
--schedHour hour
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
---- a| 
更新cron排程。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedUpdate
--policy Policy
--schedName CronBackup
--schedFreqId 5
--schedId 1
--schedActionId 1
--schedCron "0 0/5 14,18 * * ?"
--schedActive true
--schedStartDate date
--verbose
----


 a| 
排程（續...）
 a| 
列出所有排程。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedList
--verbose
----


 a| 
列出支援的排程器動作。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedActionList
--verbose
---- a| 
列出支援的排程器頻率。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedFreqList
--verbose
---- a| 
顯示排程ID的其他詳細資料。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedDetails
--schedId 1
--verbose
----


 a| 
Scdump
 a| 
在位於Snap Creator根目錄下的名為scdump的.zip檔案中、建立scdump檔案、Dumps記錄檔、組態檔及支援特定設定檔的相關資訊。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
-- profile Profile
--config Config
--action scdump
--policy Policy
--verbose
----


 a| 
SnapCreator伺服器與代理程式
 a| 
列出Snap Creator Server已知的所有代理程式狀態。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action agentStatus
--verbose
----


 a| 
SnapCreator伺服器與代理程式（續...）
 a| 
Ping Snap Creator伺服器。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action pingServer
--verbose
----


 a| 
Ping Snap Creator代理程式。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action pingAgent
--agentName host_name
--agentPort port
--verbose
---- a| 
歸檔



 a| 
根據組態檔中的設定執行歸檔記錄管理。此作業需要Snap Creator代理程式。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action arch
--verbose
---- a| 
資料保護功能



 a| 
針對特定組態設定NetApp管理主控台資料保護功能資料集。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action pmsetup
--verbose
---- a| 
顯示SnapVault 控制器的資料保護狀態：SnapMirror和SnapMirror關係。如果SnapVault 未設定SnapMirror或SnapMirror、則不會顯示結果。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action dpstatus
--verbose
---- a| 
靜止/取消靜止
 a| 
針對特定應用程式執行靜止作業。此作業需要Snap Creator代理程式。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action quiesce
--verbose
---- a| 
針對特定應用程式執行取消靜止作業。此作業需要Snap Creator代理程式。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action unquiesce
--verbose
----


 a| 
探索
 a| 
針對特定應用程式執行探索。此作業需要Snap Creator代理程式。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action discover
--verbose
----
|===