---
permalink: administration/reference_storage_error_messages.html 
sidebar: sidebar 
keywords: storage troubleshoot, error, message 
summary: 儲存相關的錯誤訊息可協助您疑難排解任何發生的問題。 
---
= 儲存錯誤訊息
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儲存相關的錯誤訊息可協助您疑難排解任何發生的問題。

下表列出錯誤代碼和訊息、以及錯誤的簡短說明和建議的解決方法。

[cols="15,35,50"]
|===
| 錯誤代碼 | 錯誤訊息 | 說明/解決方法 


 a| 
儲存設備00001
 a| 
日期格式「%s」無效：「%s」
 a| 
磁碟區複本不是由Snap Creator所建立、或是附加至複製名稱的時間戳記無效。



 a| 
儲存設備-00002
 a| 
無法擷取執行程式
 a| 
未建立用於儲存的執行程式。檢查記錄中是否有NetApp管理錯誤、這可能會顯示問題的原因。



 a| 
儲存設備-00003
 a| 
無法連線至主機
 a| 
主機無法連線。請確定本機防火牆設定正確、而且主機可以從安裝SnapCreator Server的系統ping命令。



 a| 
儲存設備-01003
 a| 
建立AutoSupport 事件ID為「%s」的動態訊息、類別為「%s」、說明為「%s」、層級為「%s」、主機名稱為「%s」失敗、並顯示錯誤「%s」。
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-01004
 a| 
對於檔案還原、來源和目的地磁碟區必須是相同的磁碟區。
 a| 
來源和目的地磁碟區不同。請提供與來源磁碟區和目的地磁碟區相同的磁碟區。



 a| 
Storage -02003
 a| 
在磁碟區[%s]上建立一致性群組Snapshot複本（%s）失敗、並顯示錯誤（s）；
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
Storage -02006
 a| 
在具有CG ID的[%s]上提交一致性群組Snapshot複本失敗、錯誤為[%s]
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
Storage -02009
 a| 
在磁碟區[%s]上建立Snapshot複本（%s）失敗、並顯示錯誤（s）
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
Storage -02015
 a| 
移除磁碟區[%s]上的Snapshot複本（%s）失敗、並顯示錯誤「%s」
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
Storage -02021
 a| 
恢復磁碟區[%s]的Snapshot複本[%s]失敗、並顯示錯誤[%s]
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
Storage -02025
 a| 
從Snapshot複本（%s）將檔案（%s）還原至（%s）失敗、並顯示錯誤（%s）
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
STEM-02028
 a| 
在SnapVault 磁碟區[%s]上建立主要的「不執行快照複本排程」失敗、並顯示錯誤「%s」
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
Storage -02034
 a| 
從SnapVault 磁碟區（%s）移除主要的不全快照複本排程失敗、並顯示錯誤（%s）
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
STEM-02038
 a| 
根據Snapshot複本（%s）建立Volume（s）的實體複本（%s）失敗、並顯示錯誤（%s）
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
Storage -02041
 a| 
根據Snapshot複本（%s）、將磁碟區（s）上的檔案（%s）複製到（s）失敗、並顯示錯誤（s）
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
STEM-02043
 a| 
在路徑上列出檔案失敗、錯誤為「%s」
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
STEM-02046
 a| 
將LUN [%s]複製到基於Snapshot複本（有空間保留空間[%s]）的[%s]、失敗並顯示錯誤[%s]
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
STAEM-02049
 a| 
從磁碟區[%s]刪除LUN [%s]失敗、並顯示錯誤[%s]
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
STAEM-02052
 a| 
列出LUN失敗、並顯示錯誤[%s]
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
Storage -02062
 a| 
為具有存取權限的主機名稱（%s）新增NFS匯出（%s）失敗、並顯示錯誤（%s）
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
Storage -02072
 a| 
在控制器[%s]上擷取SnapMirror狀態失敗、並顯示錯誤「%s」
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
STEM-02075
 a| 
擷取控制器[%s]上的SnapMirror關係失敗、並顯示錯誤「%s」
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
Storage -02082
 a| 
根據Snapshot複本（%s）更新SnapMirror關係（%s）失敗、並顯示錯誤（%s）
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
STEM-02092
 a| 
在磁碟區上列出Snapshot複本失敗、錯誤為「[%s]」
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備：02102
 a| 
將磁碟區[%s]上的Snapshot複本[%s]重新命名為[%s]失敗、並顯示錯誤[%s]
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-02112
 a| 
在SnapVault 控制器上擷取此狀態失敗、並顯示錯誤「%s」
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-02115
 a| 
擷取SnapVault 控制器[%s]上的相依關係失敗、並顯示錯誤「%s」
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-02122.
 a| 
根據SnapVault Snapshot複本（%s）更新彼此的關係（%s）失敗、並顯示錯誤（%s）
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-02132.
 a| 
根據磁碟區（%s）列出複製的磁碟區失敗、並顯示錯誤（%s）
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備：02142
 a| 
刪除磁碟區[%s]失敗、並顯示錯誤[%s]
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
Storage：02152
 a| 
列出磁碟區失敗、並顯示錯誤[%s]
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-02155
 a| 
列出Volume [%s]失敗、並顯示錯誤訊息[%s]
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-02162
 a| 
恢復磁碟區[%s]的Snapshot複本[%s]失敗、並顯示錯誤[%s]
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03001
 a| 
從叢集ONTAP 式的叢集式節點擷取Vserver（虛擬伺服器）[%s]
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-05003
 a| 
建立NetApp管理主控台資料集（%s）失敗、並顯示錯誤（%s）
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-05006
 a| 
在儲存控制器[%s]上建立NetApp管理主控台驅動的資料集（%s）備份失敗、並顯示錯誤（%s）
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-05009
 a| 
擷取資料集[%s]的NetApp管理主控台資料集狀態失敗、並顯示錯誤「%s」
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-05012
 a| 
驗證NetApp管理主控台資料集（%s）失敗、並顯示錯誤（%s）。
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-05018
 a| 
在[%s]上建立OM事件[%s]
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03002
 a| 
在LUN [%s]上對應igroup [%s]失敗、並顯示錯誤「%s」
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03005
 a| 
使磁碟區[%s]上的LUN發生故障、並顯示錯誤「%s」
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03008
 a| 
在SnapVault 磁碟區[%s]上建立主要的不執行快照複本（%s）失敗、並出現錯誤訊息（%s）
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03011
 a| 
列出資料集的NetApp管理主控台備份複本（%s）失敗、並顯示錯誤（s）
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03014
 a| 
刪除NetApp管理主控台備份版本ID（%s）失敗、並顯示錯誤（%s）
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03019
 a| 
NetApp管理主控台針對[%s]（[%s]）的備份啟動失敗、正在結束！
 a| 
檢查記錄是否有錯誤。您很可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03022
 a| 
工作ID為「%s」的NetApp管理主控台備份進度啟動失敗、正在結束！
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03025
 a| 
刪除路徑上的檔案失敗、錯誤為「%s」
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03030
 a| 
在Data ONTAP [%s]上探索叢集式的動態節點失敗
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03033
 a| 
取得系統版本詳細資料的相關資訊失敗、並顯示錯誤「[%s]」
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03036
 a| 
在路徑[%s]上建立目錄失敗、並顯示錯誤[%s]
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03039
 a| 
刪除路徑[%s]上的目錄失敗、並顯示錯誤[%s]
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03043
 a| 
在路徑上建立檔案失敗、並顯示錯誤「%s」
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03046
 a| 
資料集[%s]的NetApp管理主控台資料集修改失敗
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03049
 a| 
無法讀取檔案[%s]的檔案內容
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03052
 a| 
選項[%s]的取得選項失敗
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03055
 a| 
物件[%s]的效能計數器取得失敗
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03058
 a| 
物件[%s]的效能執行個體取得失敗
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03061
 a| 
NetApp管理主控台的資料集資訊（針對[%s]）失敗
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03064
 a| 
系統CLI命令[%s]失敗
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03067
 a| 
刪除NetApp管理主控台資料集（%s）失敗、並顯示錯誤（%s）
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03070
 a| 
根據SnapVault Snapshot複本（%s）還原此關係（%s）失敗、並顯示錯誤（%s）
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03073
 a| 
針對[%s]的CIFS匯出：[%s]失敗！
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03076
 a| 
在控制器[%s]上取得根磁碟區失敗、並顯示錯誤[%s]
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03079
 a| 
磁碟區[%s]的交會路徑取得失敗
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03082.
 a| 
系統名稱取得失敗
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03085
 a| 
控制器上的NFS服務取得失敗（%s）
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03088
 a| 
主機[%s]路徑名稱[%s]權限的NFS權限檢查失敗
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03091.
 a| 
控制器上的網路介面「Get on Controller（連線）」失敗
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-03094
 a| 
Volume [%s]上的qtree清單失敗
 a| 
檢查記錄是否有錯誤。您最可能會遇到NetApp管理錯誤。記錄可能會顯示問題的原因。



 a| 
儲存設備-04119
 a| 
列出Vserver失敗並顯示錯誤
 a| 
檢查記錄是否有錯誤。您很可能遇到「管理ONTAP 解決方案」錯誤、可能會發現問題的原因。



 a| 
vserver_tunnunnel_enabled_
 a| 
（是/否）
 a| 
設定Vim通道。如果設定為Y、則會啟用Vim通道功能。

|===