---
permalink: administration/reference_repository_error_messages.html 
sidebar: sidebar 
keywords: table, repository, error, message, global, configuration, repo 
summary: 下表列出儲存庫錯誤訊息。 
---
= 儲存庫錯誤訊息
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
下表列出儲存庫錯誤訊息。

|===
| 錯誤代碼 | 錯誤訊息 | 說明/解決方法 


 a| 
repo-01001
 a| 
全域組態不存在
 a| 
檢查globe.conf檔案是否存在於configs資料夾中。



 a| 
repo-01002
 a| 
全域組態已存在
 a| 
global.conf檔案已存在於configs資料夾中。請先刪除全域組態檔、或是更新現有的檔案。



 a| 
repo-01103
 a| 
建立全域組態失敗、錯誤為[%s]
 a| 
無法在configs資料夾中建立globe.conf檔案。根據目錄檢查執行Snap Creator的使用者權限。



 a| 
repo-01203
 a| 
更新全域組態失敗、並顯示錯誤[%s]
 a| 
無法更新configs資料夾中的glob.conf檔案。根據目錄檢查執行Snap Creator的使用者權限。



 a| 
repo-01303
 a| 
移除全域組態失敗、錯誤為[%s]
 a| 
無法移除configs資料夾中的globe.conf.檔案。檢查檔案是否存在於config資料夾中、或對照目錄檢查執行Snap Creator的使用者權限



 a| 
repo-01403
 a| 
匯出全域組態失敗、錯誤為[%s]
 a| 
讀取configs資料夾中的globe.conf.檔案失敗。檢查是否已刪除全域組態檔。



 a| 
重新提交-01503
 a| 
匯入全域組態[%s]失敗、並顯示錯誤[%s]
 a| 
無法更新configs資料夾中的glob.conf檔案。根據目錄檢查執行Snap Creator的使用者權限。



 a| 
repo-01603
 a| 
擷取全域組態失敗、錯誤為[%s]
 a| 
讀取configs資料夾中的globe.conf.檔案失敗。檢查是否已刪除全域組態檔。



 a| 
repo-02002
 a| 
設定檔[%s]已存在、請使用不同的名稱。
 a| 
已存在同名的設定檔。如果看不到設定檔、表示使用者對此設定檔沒有權限。



 a| 
repo-02003
 a| 
設定檔[%s]不存在
 a| 
檢查您的設定檔是否已重新命名或刪除。此外、使用者可能沒有此設定檔的權限。



 a| 
重新報告-0103
 a| 
建立全域設定檔組態（%s）失敗、並顯示錯誤（%s）
 a| 
無法在設定檔中建立globe.conf.檔案。根據目錄檢查執行Snap Creator的使用者權限。



 a| 
重新報告-02106
 a| 
建立設定檔組態（%s）失敗、錯誤為（s）
 a| 
無法在組態資料夾中建立設定檔。根據目錄檢查執行Snap Creator的使用者權限。



 a| 
重新報告-02203
 a| 
更新設定檔組態（%s）失敗、錯誤為（s）
 a| 
無法更新組態資料夾中的設定檔。根據目錄檢查執行Snap Creator的使用者權限。



 a| 
repo-02213
 a| 
重新命名設定檔（%s）至（s）失敗、錯誤為（s）
 a| 
無法重新命名組態資料夾中的設定檔。根據目錄檢查執行Snap Creator的使用者權限、或檢查您的設定檔是否已重新命名或刪除。



 a| 
重新回應-02303
 a| 
移除設定檔組態（%s）失敗
 a| 



 a| 
repo-02403
 a| 
匯出設定檔組態（%s）失敗、錯誤為（s）
 a| 



 a| 
repo-02503
 a| 
匯入設定檔組態（%s）失敗、錯誤為（s）
 a| 



 a| 
重新報告-09603
 a| 
擷取全域設定檔失敗、錯誤為[%s]
 a| 



 a| 
重新規劃-05606
 a| 
擷取設定檔（%s）失敗、錯誤為（s）
 a| 



 a| 
repo-02703
 a| 
列出設定檔失敗、錯誤為[%s]
 a| 
列出設定檔失敗。檢查組態資料夾路徑。



 a| 
repo-03002
 a| 
設定檔[%s]的組態[%s]已存在
 a| 
指定設定檔已存在名稱相同的組態檔。請選擇不同的名稱。



 a| 
repo-0103
 a| 
為設定檔[%s]建立組態[%s]失敗、錯誤為[%s]
 a| 



 a| 
repo-03203
 a| 
更新設定檔[%s]的組態[%s]失敗、錯誤為[%s]
 a| 



 a| 
repo-03212
 a| 
將設定檔[%s]的組態設定檔[%s]重新命名為[%s]失敗
 a| 
無法從設定檔重新命名組態。檢查您的組態是否已重新命名或刪除、並檢查執行Snap Creator的使用者對目錄的權限。



 a| 
repo-0303
 a| 
從設定檔[%s]移除組態[%s]失敗
 a| 
無法從組態資料夾中的設定檔刪除組態。根據目錄檢查執行Snap Creator的使用者權限。



 a| 
請參閱repo-0333
 a| 
匯出設定檔為[%s]的組態為[%s]失敗、並顯示錯誤為[%s]
 a| 



 a| 
重新報告-0503
 a| 
將組態[%s]匯入設定檔[%s]失敗、並顯示錯誤[%s]
 a| 



 a| 
請參閱repo-09603
 a| 
從設定檔[%s]擷取組態[%s]失敗、並顯示錯誤[%s]
 a| 



 a| 
請參閱repo-0703
 a| 
從設定檔中列出組態失敗、並顯示錯誤[%s]
 a| 



 a| 
repo-04003
 a| 
讀取設定檔[%s]的目錄、組態[%s]和時間戳記[%s]失敗、並顯示錯誤[%s]
 a| 



 a| 
repo-04103
 a| 
寫入設定檔[%s]的目錄、組態[%s]和時間戳記[%s]失敗、並顯示錯誤[%s]
 a| 



 a| 
repo-04203
 a| 
清除設定檔[%s]的目錄、組態[%s]和時間戳記[%s]失敗、並顯示錯誤[%s]
 a| 



 a| 
repo-04303
 a| 
為設定檔[%s]和組態[%s]建立目錄失敗、並顯示錯誤[%s]
 a| 



 a| 
重新報告-04304
 a| 
組態[%s]不存在
 a| 



 a| 
請重新執行04309
 a| 
新增原則物件失敗（%s）
 a| 
資料庫錯誤；請檢查堆疊追蹤以取得更多資訊。



 a| 
重新報告-04313
 a| 
移除原則ID的原則物件失敗：%s
 a| 
資料庫錯誤；請檢查堆疊追蹤以取得更多資訊。



 a| 
repo-04315
 a| 
更新原則物件失敗：%s
 a| 
資料庫錯誤；請檢查堆疊追蹤以取得更多資訊。



 a| 
repo-04316
 a| 
無法列出原則
 a| 
資料庫錯誤；請檢查堆疊追蹤以取得更多資訊。



 a| 
repo-04321
 a| 
新增備份類型物件失敗（%s）
 a| 
資料庫錯誤；請檢查堆疊追蹤以取得更多資訊。



 a| 
repo-04323
 a| 
備份類型ID不存在備份類型項目：%s
 a| 
通過有效的備份類型。



 a| 
repo-04325
 a| 
移除備份類型ID的備份類型物件失敗：%s
 a| 
資料庫錯誤；請檢查堆疊追蹤以取得更多資訊。



 a| 
repo-04327
 a| 
更新備份類型物件失敗：%s
 a| 
資料庫錯誤；請檢查堆疊追蹤以取得更多資訊。



 a| 
repo-04328
 a| 
無法列出備份類型
 a| 
資料庫錯誤；請檢查堆疊追蹤以取得更多資訊。



 a| 
repo-04333
 a| 
新增排程器工作物件失敗（%s）
 a| 
資料庫錯誤；請檢查堆疊追蹤以取得更多資訊。



 a| 
重新報告-04335
 a| 
工作ID不存在排程器工作項目：%s
 a| 
通過有效的排程器工作。



 a| 
重新命名：repo-043337
 a| 
移除工作ID的排程器工作物件失敗：%s
 a| 
資料庫錯誤；請檢查堆疊追蹤以取得更多資訊。



 a| 
重新報告-04339.
 a| 
更新排程器工作物件失敗：%s
 a| 
資料庫錯誤；請檢查堆疊追蹤以取得更多資訊。



 a| 
repo-04340
 a| 
無法列出排程器工作
 a| 
資料庫錯誤；請檢查堆疊追蹤以取得更多資訊。



 a| 
repo-04341
 a| 
新增原則物件失敗、具有相同名稱的原則[%s]已存在
 a| 
同名原則已存在；請嘗試使用不同名稱。



 a| 
repo-04342
 a| 
新增備份類型物件失敗、已存在名稱相同的備份類型（%s）
 a| 
同名的備份類型已存在；請嘗試使用不同的名稱。



 a| 
repo-04343
 a| 
新增排程器物件失敗、具有相同工作名稱的排程器（%s）已存在
 a| 



 a| 
repo-04344
 a| 
無法更新設定檔[%s]。設定檔為空白。
 a| 



 a| 
repo-04345
 a| 
新增原則時、原則類型不可為null
 a| 



 a| 
repo-04346
 a| 
儲存物件不可為null
 a| 



 a| 
重新報告-04347
 a| 
新增儲存物件失敗、具有相同名稱/IP的儲存設備（%s）已存在
 a| 



 a| 
repo-04348
 a| 
無法擷取儲存詳細資料。資料庫錯誤！
 a| 



 a| 
重新報告-04349
 a| 
無效的主機名稱。不存在具有主機名稱/IP [%s]的儲存設備
 a| 



 a| 
repo-0350
 a| 
主機名稱不可為null
 a| 
無效的主機名稱



 a| 
repo-04335
 a| 
刪除儲存設備（%s）失敗、並顯示錯誤（%s）
 a| 
無法刪除儲存設備。資料庫錯誤！



 a| 
重新報告-04755
 a| 
更新儲存設備[%s]失敗、並顯示錯誤[%s]
 a| 
無法更新儲存設備。資料庫錯誤！



 a| 
repo-04356.
 a| 
叢集物件不可為null
 a| 



 a| 
重新報告-0358.
 a| 
新增儲存設備（%s）失敗、錯誤為（s）
 a| 



 a| 
重新報告-0359
 a| 
更新叢集[%s]失敗、並顯示錯誤[%s]
 a| 



 a| 
repo-04360
 a| 
新增叢集物件失敗、具有相同名稱/IP的叢集[%s]已存在
 a| 
具有相同主機名稱的叢集已存在

|===