---
permalink: administration/task_creating_global_configuration_files.html 
sidebar: sidebar 
keywords: global, configuration, storage, controller, file, create, backup, super, profile 
summary: 您可以建立全域組態檔、將儲存控制器、儲存虛擬機器（SVM\）或VMware認證組態與備份原則分開。 
---
= 建立全域組態檔
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以建立全域組態檔、將儲存控制器、儲存虛擬機器（SVM）或VMware認證組態與備份原則分開。

全域組態檔可讓您控制存取、以及處理備份與還原作業。

您可以建立兩種類型的全域組態檔：

* *超級全球*
+
此組態適用於所有設定檔中的所有組態。

* *設定檔全球*
+
此組態適用於在設定檔中建立的所有組態。

+
.. 從SnapCreator GUI的主功能表中、選取*管理*>*全域組態*。
.. 在「全域組態」窗格中、按一下「*建立全域*」。
+
「全域組態」的組態精靈會在右窗格中開啟。

.. 完成組態精靈以建立組態檔：
+
... 在*組態*頁面上、選取全域組態類型（超級全域或設定檔全域）。
+
組態檔的名稱預設為全域。您無法變更此名稱。

+
如果您選取「設定檔全域」作為全域組態類型、請選取設定檔。

+

NOTE: 預設會啟用密碼加密、以防止密碼以明文形式顯示在組態檔中。

... 在「外掛程式類型」頁面上、選取外掛程式的類型。
+
您在精靈中前進到的頁面取決於您選取的選項。

+
|===
| 外掛程式類型選項 | 下一頁 | 下一頁 


 a| 
虛擬化外掛程式
 a| 
*虛擬化外掛程式*選取要設定的外掛程式。
 a| 
*驗證資訊*提供所選外掛程式選項的驗證資訊。



 a| 
無
 a| 
*儲存連線設定*
 a| 
--

--
|===
+
如需外掛程式認證的詳細資訊、請參閱外掛程式文件。

... 在「Storage Connection Settings（儲存連線設定）」頁面上、選取傳輸類型（HTTP或HTTPS）。
+
顯示所選傳輸類型的標準連接埠。如果儲存系統使用非標準連接埠、請在連接埠欄位中輸入連接埠資訊。

... 在「控制器/vserver認證」頁面上、輸入此組態檔中包含磁碟區的每個儲存控制器或SVM的IP位址和登入認證。
+

NOTE: 您必須在組態中新增至少一個儲存控制器或SVM。若要使用Vim通道功能、請選取「* IP通道*」核取方塊（僅適用於叢集）。

... 在「Controller Credentials（控制器認證）」頁面上、確認控制器顯示正確的資訊。
+
如果需要變更、請選取控制器、然後按一下*編輯*。

... 在DFM / OnCommand設定頁面上、如果您想要將Snap Creator組態與NetApp OnCommand 效益管理工具整合、請選取並提供詳細資料。
... 檢閱摘要、然後按一下「*完成*」。





