---
permalink: administration/task_customizing_the_default_keystore.html 
sidebar: sidebar 
keywords: keystore, certificate, keytool, windows, unix 
summary: 您可以使用Windows和UNIX上可用的keytool,來自訂預設的Keystore或憑證。 
---
= 自訂預設的Keystore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用Windows和UNIX上可用的keytool,來自訂預設的Keystore或憑證。

keytool命令由Java提供。在某些環境中、您可能必須切換至Java安裝目錄、才能執行keytools命令。

SnapCreator不支援信任存放區。

. 停止SnapCreator Agent。
. 使用單一憑證產生新的Keystore：
+
「keytool-genkeypair -alias alias _name -keystore keystore_file -keypass private_key_password-storepass keyKeystore密碼」

+
keytool-genkeypair -alias servicekey -keystore serviceKeystore.jks -keypass kypswd123 -storepass kystrpswd123

. 將Keystore檔案複製到scAgent4.3.0/etc/目錄。
. 更新Snap Creator Agent組態檔（scagent4.3.0/etc/iled_commands.config）中的Keystore檔案=Keystore檔案和Keystore密碼參數。
. 啟動SnapCreator Agent。


*相關資訊*

xref:task_starting_verifying_and_stopping_the_snap_creator_agent_on_windows.adoc[在Windows上啟動、驗證及停止Snap Creator Agent]

xref:task_starting_verifying_and_stopping_the_snap_creator_agent_on_unix.adoc[在UNIX上啟動、驗證及停止Snap Creator Agent]
