---
permalink: administration/task_creating_configuration_files_using_sc_gui.html 
sidebar: sidebar 
keywords: configuration, file, wizard, gui, management 
summary: 您可以使用組態精靈來建立組態檔。 
---
= 正在建立組態檔
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用組態精靈來建立組態檔。

. 從SnapCreator GUI的主功能表中、選取*管理*>*組態*。
. 在「設定檔與組態」窗格中、以滑鼠右鍵按一下您要放置新組態檔的設定檔、然後選取*「新組態」*。
+
「組態精靈」會在右窗格中開啟。

. 
+
.. 在「組態」頁面上、輸入組態檔的名稱。
+

NOTE: 預設會啟用密碼加密、以防止密碼以明文形式顯示在組態檔中。

.. 在「外掛程式類型」頁面上、選取外掛程式的類型。
+
您在組態精靈中前進到的頁面取決於您所選的選項。

+
|===
| 外掛程式類型選項 | 下一頁 | 下一頁 


 a| 
應用程式外掛程式
 a| 
*應用程式外掛程式*選取要設定的外掛程式。
 a| 
*外掛參數*提供與所選外掛程式選項相關的組態詳細資料。



 a| 
虛擬化外掛程式
 a| 
*虛擬化外掛程式*選取要設定的外掛程式。
 a| 
*外掛參數*提供與所選外掛程式選項相關的組態詳細資料。



 a| 
社群外掛程式
 a| 
*社群外掛程式*選取要設定的外掛程式。
 a| 
*外掛參數*提供與所選外掛程式選項相關的組態詳細資料。



 a| 
無（如果您未使用外掛程式）
 a| 
*代理程式組態*
 a| 
--

--
|===
+
如需外掛程式參數與組態的詳細資訊、請參閱外掛程式文件。

.. 在「代理程式組態」頁面上、輸入Snap Creator Agent的組態資訊。
.. 在「Storage Connection Settings（儲存連線設定）」頁面上、選取傳輸類型（HTTP或HTTPS）。
+
顯示所選傳輸類型的標準連接埠。如果儲存系統使用非標準連接埠、請在連接埠欄位中輸入連接埠資訊。

.. 在「控制器/vserver認證」頁面上、輸入此組態檔中包含磁碟區的每個儲存控制器SVM的IP位址和登入認證。
+

NOTE: 您必須在組態中新增至少一個儲存控制器或SVM。

.. 在「控制器/虛擬伺服器磁碟區」窗格中、選取您要包含的每個磁碟區、然後將其拖曳到右窗格、或按一下右箭頭將磁碟區移到右窗格、然後按一下「*儲存*」。
+

IMPORTANT: 如果您打算將Snapshot複本複製到Snapmirror或SnapVault Sf目的地、則在此步驟中輸入的SVM名稱必須與您建立Snapmirror或SnapVault SVM關係時所使用的SVM名稱完全相同。如果您在建立關聯時指定了完整網域名稱、則必須在此步驟中指定完整網域名稱、無論Snap Creator是否能找到含有您所提供資訊的SVM。您用於名稱的案例（大小寫或大小寫）相當顯著。

+
您可以使用SnapMirror show命令檢查主儲存系統上SVM的名稱：

+
[listing]
----
snapmirror show -destination-path destination_SVM:destination_volume
----
+
其中destination_Svm_name是目的地系統上SVM的名稱、destination_volume是該磁碟區。

.. 在「Controller Credentials（控制器認證）」頁面上、確認控制器顯示正確的資訊。
+
如果需要變更、請選取控制器、然後按一下*編輯*。

.. 在「Snapshot Details」（Snapshot詳細資料）頁面上、提供Snapshot複本詳細資料。
+
|===
| 欄位 | 說明 


 a| 
Snapshot複本名稱
 a| 
可讓您指定Snapshot複本名稱、Snapshot複本的名稱通常與組態檔相同、不過Snapshot複本名稱可以反映正在備份的資料。

+附註：指定Snapshot複本名稱時、請勿使用特殊字元。



 a| 
Snapshot複製標籤
 a| 
可讓您指定Snapshot複本標籤此選項適用於叢集Data ONTAP 式的8.2及更新版本。對於叢集式的發行版、此欄位不會提供任何功能。Data ONTAP Data ONTAP



 a| 
原則類型
 a| 
可讓您選取原則類型有兩個選項：

*** 原則：此選項會啟用Snapshot複本原則區域中所示的其中一個內建原則、並指定保留（保留的備份數）。
*** 使用原則物件：如果已建立原則物件、則應選取此選項。




 a| 
Snapshot複製原則
 a| 
提供選項以選取要啟用的原則



 a| 
防止刪除Snapshot複本
 a| 
可讓您決定是否禁止刪除Snapshot複本



 a| 
原則保留期限
 a| 
可讓您指定原則保留期限



 a| 
命名慣例
 a| 
可讓您指定備份的命名慣例（最近或時間戳記）。SAP HANA、VIBE和Domino等外掛程式不支援「最近」。

+

|===
.. 在「Snapshot Details（Snapshot詳細資料）」繼續頁面上、設定適用於您環境的任何其他設定。
.. 在Data Protection（資料保護）頁面上、選擇SnapVault 是否需要與SnapMirror或支援作業整合。
+
如果選擇SnapMirror或SnapVault SnapMirror技術、則需要其他資訊。對於SnapMirror和SnapVault SnapMirror技術、您必須提供儲存系統名稱、而非IP位址。

.. 在DFM / OnCommand設定頁面上、如果您想要將Snap Creator組態與NetApp OnCommand 效益管理工具整合、請選取並提供詳細資料。
.. 檢閱摘要、然後按一下「*完成*」。



