---
permalink: installation/task_upgrading_snap_creator_agent_4_1_x_on_windows.html 
sidebar: sidebar 
keywords: upgrading, snap, creator, agent, 4.1.x, windows 
summary: 您可以從Windows上的Snap Creator Agent 4.1.x升級。 
---
= 升級Windows上的Snap Creator Agent 4.1.x
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從Windows上的Snap Creator Agent 4.1.x升級。

* 在備份Snap Creator Agent目錄之前、您已停止Snap Creator Agent服務（「napcreatoragentservice」）、以確保備份資料已完成。
+
例如、您可以使用「服務」嵌入式管理單元來停止服務：

+
.. 選擇* Start*>* Run*、然後輸入「服務msc」。
.. 找到並選取Snap Creator Agent服務、然後停止服務。或者、您也可以開啟命令提示字元、然後輸入下列命令：


+
[listing]
----
sc stop snapcreatoragentservice
----
* 您已在Snap Creator Agent目錄（C:\Program Files\NetApp\NetApp_Snap_Creator_Framework\scagent4.1.x）中備份下列目錄及所有相關子目錄與檔案：
+
** SnapCreator Agent屬性（.\etc）、其中包含允許的_commands.config和agent.properties檔案
** 記錄（.\logs）
** 外掛程式（..\plugins）*注意：*請勿刪除您建立的Snap Creator 4.1.x備份複本。




下列步驟所提供的路徑、是指Windows的預設安裝路徑。如果未使用預設值、路徑資訊可能會與安裝路徑不同。

. 如果您尚未這麼做、請停止SnapCreator Agent服務。
+
如需停止服務的相關資訊、請參閱本主題稍早所提供的詳細資料。

. 若要解除安裝Snap Creator（適用於Windows）、請選取* Start*>* Programs*>* Snap Creator*>*解除安裝NetApp Snap Creator Framework*。
+
如需詳細資訊、請參閱在Windows上解除安裝Snap Creator的相關資訊。

. 安裝最新的Snap Creator Agent。
+
如需詳細資訊、請參閱在Windows上安裝Snap Creator Agent的相關資訊。

. 如果您在安裝最新的Snap Creator Server時選擇以服務形式啟動Snap Creator Agent、請停止服務。
+
如需停止服務的相關資訊、請參閱本主題稍早所提供的詳細資料。

. 將備份的Snap Creator 4.1.x記錄目錄複製到最新位置（C:\Program Files\NetApp\Snap_Creator_Framework\scAgent4.1.x\logs）。
. 將備份的Snap Creator 4.1.x外掛程式目錄複製到最新位置（C:\Program Files\NetApp\Snap_Creator_Framework\scAgent4.1.x\plugins）。
. 將備份的Snap Creator 4.1.x代理程式內容目錄複製到最新位置（C:\Program Files\NetApp\Snap_Creator_Framework\scagent4.1.x\etc）。
. 執行下列其中一項動作、啟動Snap Creator Agent服務：
+
** 使用「服務」嵌入式管理單元並啟動服務。
** 在命令提示字元中輸入下列命令：
+
[listing]
----
sc start snapcreatoragentservice
----


+

NOTE: 對allowed_commands.config或agent.properties檔案所做的任何變更、都需要在變更執行時重新啟動Snap Creator Agent。


